# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sham_rack}
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Williams"]
  s.date = %q{2010-03-11}
  s.description = %q{ShamRack plumbs Net::HTTP directly into Rack, for quick and easy HTTP testing.}
  s.email = %q{mdub@dogbiscuit.org}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGES.markdown",
     "README.markdown",
     "Rakefile",
     "benchmark/benchmark.rb",
     "benchmark/hello_app.rb",
     "lib/sham_rack.rb",
     "lib/sham_rack/core_ext/net/http.rb",
     "lib/sham_rack/http.rb",
     "lib/sham_rack/registry.rb",
     "lib/sham_rack/stub_web_service.rb",
     "lib/sham_rack/version.rb",
     "sham_rack.gemspec",
     "spec/sham_rack/stub_web_service_spec.rb",
     "spec/sham_rack_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mdub/sham_rack}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{shamrack}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Net::HTTP-to-Rack plumbing}
  s.test_files = [
    "spec/sham_rack/stub_web_service_spec.rb",
     "spec/sham_rack_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

